env:
  contexts:
  - excludePaths: []
    name: baseline
    urls:
    - http://host.docker.internal:3000
  parameters:
    failOnError: true
    progressToStdout: false
jobs:
- parameters:
    enableTags: false
    maxAlertsPerRule: 10
  type: passiveScan-config
- parameters:
    maxDuration: 2
    url: http://host.docker.internal:3000
  type: spider
- parameters:
    maxDuration: 0
  type: passiveScan-wait
- parameters:
    format: Long
    summaryFile: /home/zap/zap_out.json
  rules:
  - action: INFO
    customMessage: ''
    id: 10038
  - action: INFO
    customMessage: ''
    id: 10049
  - action: INFO
    customMessage: ''
    id: 10063
  - action: INFO
    customMessage: ''
    id: 10096
  - action: INFO
    customMessage: ''
    id: 10098
  - action: INFO
    customMessage: ''
    id: 10109
  - action: INFO
    customMessage: ''
    id: 10110
  - action: INFO
    customMessage: ''
    id: 90004
  type: outputSummary
- parameters:
    reportDescription: ''
    reportDir: /zap/wrk/
    reportFile: /zap/wrk/security/reports/zap-baseline.html
    reportTitle: ZAP Scanning Report
    template: traditional-html
  type: report
- parameters:
    reportDescription: ''
    reportDir: /zap/wrk/
    reportFile: /zap/wrk/security/reports/zap-baseline.md
    reportTitle: ZAP Scanning Report
    template: traditional-md
  type: report
- parameters:
    reportDescription: ''
    reportDir: /zap/wrk/
    reportFile: /zap/wrk/security/reports/zap-baseline.json
    reportTitle: ZAP Scanning Report
    template: traditional-json
  type: report
